### ISSUE TITLE
Pull access denied?

### ISSUE THREAD

**Issue by VYRNACH** [ripps818/docker-palworld-dedicated-server-wine#13]
when running **docker-compose up -d && docker-compose logs -f** I get the following errors. Please help

```
~/PalServer$ sudo docker-compose up -d && docker-compose logs -f
Pulling palworld-dedicated-server (ripps818/palworld-dedicated-server-wine:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling palworld-dedicated-server (ripps818/palworld-dedicated-server-wine:latest)...
ERROR: pull access denied for ripps818/palworld-dedicated-server-wine, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by ripps818** [comment]
Try `ghcr.io/ripps818/docker-palworld-dedicated-server-wine` instead. I haven't uploaded the images to dockerhub, only github. I'll edit the docker-compose.yml to reflect that.

**Comment by VYRNACH** [comment]
Please clarify on the correct image to use. I first tried "ghcr.io/ripps818/**docker-palworld-dedicated-server-wine**" as mentioned here and it seems to work until it failed to install the game files. I don't know how to proceed as I'm unable to find the log files to show why
```
palworld-wine-server  | >>> Doing a fresh install of the gameserver...
palworld-wine-server exited with code 0
```

Then I inspect the recently modified docker-compose.yml and there it's shown as "ghcr.io/ripps818/**palworld-dedicated-server-wine**:latest". Upon trying this one I get:
```
[+] Running 1/1
 ✘ palworld-dedicated-server Error                                                                                                 1.5s
Error response from daemon: Head "https://ghcr.io/v2/ripps818/palworld-dedicated-server-wine/manifests/latest": denied
```
Please help

**Comment by ripps818** [comment]
Yes, sorry there was a typo in the docker-compose.yaml. I've since updated it.

I don't know if this is the same issue, but I used to have a similar problem with docker and folder write permission on my Fedora Laptop. It turns out it was Selinux preventing it. I think you can disable selinux in the container by adding this to your yaml:
```
security_opt:
  - label:disable
```
or you can flag the file or folder itself with:
`chcon system_u:object_r:container_file_t:s0 /path/to/folder`
