### ISSUE TITLE
Threat Detected: Aborting Server Start

### ISSUE THREAD

**Issue by ghost** [ripps818/docker-palworld-dedicated-server-wine#21]
![image](https://github.com/ripps818/docker-palworld-dedicated-server-wine/assets/47906826/35caec92-3f14-4c74-8cef-38ed3b6c336f)

Get this every time i try to start the image, ive set the env variables correctly. Any assistance?

**Comment by ripps818** [comment]
It means the variable ADMIN_PASSWORD in default.env hasn't been changed in the container. If you're using the docker-compose.yml, be sure to change the passwords in default.env
